### ISSUE TITLE
Can't seem to get module 'requests' working

### ISSUE THREAD

**Issue by bossanova808** [matthuisman/docker-kodi-headless#3]
So I've copied the module (`script.module.requests`) into the addons folder, and re-started the container (twice actually)... I read that thread somewhere where you mention addons get automatically enabled.

I need to get it working so I can use the tvdb (new, python) scraper.  It's used by heaps of addons though, so I'd imagine pretty useful generally.

In the logs it definitely says:
```
2021-08-12 18:28:01.196 T:274      INFO <general>: CAddonMgr::FindAddons: script.module.requests v2.25.1+matrix.1 installed
```

However when Sonarr goes to poke a show in to the library, I see these:

```
2021-08-12 18:28:33.781 T:290     DEBUG <general>: CPythonInvoker(2, /config/.kodi/addons/metadata.tvdb.com.python/scraper.py): start processing
2021-08-12 18:28:33.927 T:290     DEBUG <general>: -->Python Interpreter Initialized<--
2021-08-12 18:28:33.927 T:290     DEBUG <general>: 
                                                   
2021-08-12 18:28:33.927 T:290     DEBUG <general>: CPythonInvoker(2, /config/.kodi/addons/metadata.tvdb.com.python/scraper.py): the source file to load is "/config/.kodi/addons/metadata.tvdb.com.python/scraper.py"
2021-08-12 18:28:33.927 T:290     DEBUG <general>: CPythonInvoker(2, /config/.kodi/addons/metadata.tvdb.com.python/scraper.py): setting the Python path to /config/.kodi/addons/metadata.tvdb.com.python:/usr/lib/python36.zip:/usr/lib/python3.6:/usr/lib/python3.6/lib-dynload
2021-08-12 18:28:33.927 T:290     DEBUG <general>: CPythonInvoker(2, /config/.kodi/addons/metadata.tvdb.com.python/scraper.py): entering source directory /config/.kodi/addons/metadata.tvdb.com.python
2021-08-12 18:28:33.927 T:290     DEBUG <general>: CPythonInvoker(2, /config/.kodi/addons/metadata.tvdb.com.python/scraper.py): instantiating addon using automatically obtained id of "metadata.tvdb.com.python" dependent on version 3.0.0 of the xbmc.python api
2021-08-12 18:28:34.593 T:290     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'requests'
                                                   Traceback (most recent call last):
                                                     File "/config/.kodi/addons/metadata.tvdb.com.python/scraper.py", line 3, in <module>
                                                       from resources.lib import actions
                                                     File "/config/.kodi/addons/metadata.tvdb.com.python/resources/lib/actions.py", line 10, in <module>
                                                       import requests
                                                   ModuleNotFoundError: No module named 'requests'
                                                   -->End of Python script error report<--
                                                   
2021-08-12 18:28:34.593 T:290     DEBUG <general>: onExecutionDone(2, /config/.kodi/addons/metadata.tvdb.com.python/scraper.py)
2021-08-12 18:28:34.614 T:290      INFO <general>: Python interpreter stopped
2021-08-12 18:28:34.614 T:290     DEBUG <general>: Thread LanguageInvoker 140200701454080 terminating
2021-08-12 18:28:34.631 T:276     ERROR <general>: GetDirectory - Error getting plugin://metadata.tvdb.com.python/?action=getepisodelist&url=320766&pathSettings=%7b%22RatingS%22%3a0%2c%22absolutenumber%22%3afalse%2c%22dvdorder%22%3afalse%2c%22language%22%3a%22en%22%2c%22token%22%3a%22eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTYyODI3NTEsImlkIjoiS29kaSIsIm9yaWdfaWF0IjoxNjE1Njc3OTUxfQ.zqeQ2JpaillB_skXnYb0_wq-ANule3wzpXrJij56MTtuJQbDUQI2qf3EHP5lW3ChWduEdh2dDF_gm_ZD4v6AWPxT1IGnoFWTCyhECH6jOCOxKKfWKNllCO0cH38uHR22F-isBa44OmwPGIifqNh2CYVi6kwZIQbG6JNQSkc_Zyx0q5O7iCxjAwQMGtgBeJpffVWLpR1Z9qI-T6auMxorONCMu1FY16JySYxqiovxML1FBqw8HsQPjiCdALY486kMlXfay5F6Nzc9qLvlZQh2gATc4wqluTyZYwPAoeYYFiN0CyG60PJbNWXbL58WLRletfx5sHcQsSuLJQ5yCVHm0A%22%7d
2021-08-1

```

An idea how I can get that module to actually be available to Kodi??

(BTW - thanks so much for the work on this - going to be super handy once I can get it scraping things!!)

**Comment by matthuisman** [comment]
requests isn't a dependency of metadata.tvdb.com.python https://github.com/xbmc/metadata.tvdb.com.python/blob/main/addon.xml
so it's library path won't be added to the  Python path when calling metadata.tvdb.com.python

requests is a dependency of script.module.tvdbsimple - https://github.com/xbmc/script.module.tvdbsimple/blob/main/addon.xml
so you need to install that and also script.module.trakt

**Comment by bossanova808** [comment]
Yeah so it turns out a whole bunch of others too - chardet, certifi, urllib3 etc.  In the end I just copied script.modules.* from a non headless installation over rather than keep trying to unwind the chain...there's no harm having them there I guess!

**Comment by bossanova808** [comment]
(Thanks for the guidance, I meant to add!)

**Comment by bossanova808** [comment]
I am still struggling actually..arrow is definitely installed, I can see that the addon is invoked **with arrow in the path** as per the log below, but _still_ it can't find the arrow module

(arrow is a listed dependency here - https://github.com/Razzeee/script.module.trakt/blob/main/addon.xml )

I copied all the modules from a working Kodi (windows).

```
2021-08-13 08:30:36.718 T:274     DEBUG <general>: CAddonDatabase: script.module.arrow has been installed.
...
2021-08-13 14:28:48.415 T:347     DEBUG <general>: StartScript - calling plugin The TVDB (new)('plugin://metadata.tvdb.com.python/','4','?action=getepisodelist&url=361948&pathSettings=%7b%22RatingS%22%3a0%2c%22absolutenumber%22%3afalse%2c%22dvdorder%22%3afalse%2c%22language%22%3a%22en%22%2c%22token%22%3a%22eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTYyODI3NTEsImlkIjoiS29kaSIsIm9yaWdfaWF0IjoxNjE1Njc3OTUxfQ.zqeQ2JpaillB_skXnYb0_wq-ANule3wzpXrJij56MTtuJQbDUQI2qf3EHP5lW3ChWduEdh2dDF_gm_ZD4v6AWPxT1IGnoFWTCyhECH6jOCOxKKfWKNllCO0cH38uHR22F-isBa44OmwPGIifqNh2CYVi6kwZIQbG6JNQSkc_Zyx0q5O7iCxjAwQMGtgBeJpffVWLpR1Z9qI-T6auMxorONCMu1FY16JySYxqiovxML1FBqw8HsQPjiCdALY486kMlXfay5F6Nzc9qLvlZQh2gATc4wqluTyZYwPAoeYYFiN0CyG60PJbNWXbL58WLRletfx5sHcQsSuLJQ5yCVHm0A%22%7d','resume:false')
2021-08-13 14:28:48.415 T:349     DEBUG <general>: Thread LanguageInvoker start, auto delete: false
2021-08-13 14:28:48.415 T:349      INFO <general>: initializing python engine.
2021-08-13 14:28:48.415 T:349     DEBUG <general>: CPythonInvoker(4, /config/.kodi/addons/metadata.tvdb.com.python/scraper.py): start processing
2021-08-13 14:28:48.534 T:349     DEBUG <general>: -->Python Interpreter Initialized<--
2021-08-13 14:28:48.534 T:349     DEBUG <general>: 
                                                   
2021-08-13 14:28:48.534 T:349     DEBUG <general>: CPythonInvoker(4, /config/.kodi/addons/metadata.tvdb.com.python/scraper.py): the source file to load is "/config/.kodi/addons/metadata.tvdb.com.python/scraper.py"
2021-08-13 14:28:48.535 T:349     DEBUG <general>: CPythonInvoker(4, /config/.kodi/addons/metadata.tvdb.com.python/scraper.py): setting the Python path to /config/.kodi/addons/metadata.tvdb.com.python:/config/.kodi/addons/script.module.arrow/lib:/config/.kodi/addons/script.module.certifi/lib:/config/.kodi/addons/script.module.chardet/lib:/config/.kodi/addons/script.module.dateutil/lib:/config/.kodi/addons/script.module.idna/lib:/config/.kodi/addons/script.module.requests/lib:/config/.kodi/addons/script.module.six/lib:/config/.kodi/addons/script.module.trakt/lib:/config/.kodi/addons/script.module.tvdbsimple/lib:/config/.kodi/addons/script.module.urllib3/lib:/usr/lib/python36.zip:/usr/lib/python3.6:/usr/lib/python3.6/lib-dynload
2021-08-13 14:28:48.535 T:349     DEBUG <general>: CPythonInvoker(4, /config/.kodi/addons/metadata.tvdb.com.python/scraper.py): entering source directory /config/.kodi/addons/metadata.tvdb.com.python
2021-08-13 14:28:48.535 T:349     DEBUG <general>: CPythonInvoker(4, /config/.kodi/addons/metadata.tvdb.com.python/scraper.py): instantiating addon using automatically obtained id of "metadata.tvdb.com.python" dependent on version 3.0.0 of the xbmc.python api
2021-08-13 14:28:49.951 T:349     DEBUG <general>: metadata.tvdb.com.python: Called addon with params: ['plugin://metadata.tvdb.com.python/', '4', '?action=getepisodelist&url=361948&pathSettings=%7b%22RatingS%22%3a0%2c%22absolutenumber%22%3afalse%2c%22dvdorder%22%3afalse%2c%22language%22%3a%22en%22%2c%22token%22%3a%22eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTYyODI3NTEsImlkIjoiS29kaSIsIm9yaWdfaWF0IjoxNjE1Njc3OTUxfQ.zqeQ2JpaillB_skXnYb0_wq-ANule3wzpXrJij56MTtuJQbDUQI2qf3EHP5lW3ChWduEdh2dDF_gm_ZD4v6AWPxT1IGnoFWTCyhECH6jOCOxKKfWKNllCO0cH38uHR22F-isBa44OmwPGIifqNh2CYVi6kwZIQbG6JNQSkc_Zyx0q5O7iCxjAwQMGtgBeJpffVWLpR1Z9qI-T6auMxorONCMu1FY16JySYxqiovxML1FBqw8HsQPjiCdALY486kMlXfay5F6Nzc9qLvlZQh2gATc4wqluTyZYwPAoeYYFiN0CyG60PJbNWXbL58WLRletfx5sHcQsSuLJQ5yCVHm0A%22%7d', 'resume:false']
2021-08-13 14:28:49.951 T:349     DEBUG <general>: metadata.tvdb.com.python: Find episodes of tvshow with id 361948
2021-08-13 14:28:50.101 T:349   WARNING <general>: Attempt to use invalid handle 4
2021-08-13 14:28:50.101 T:349      INFO <general>: CPythonInvoker(4, /config/.kodi/addons/metadata.tvdb.com.python/scraper.py): script successfully run
2021-08-13 14:28:50.102 T:347     DEBUG <general>: GetVideoDetails: Reading episode '8609547' using The TVDB (new) scraper (file: '/config/.kodi/addons/metadata.tvdb.com.python/', content: 'tvshows', version: '1.0.3')
2021-08-13 14:28:50.103 T:347     DEBUG <general>: StartScript - calling plugin The TVDB (new)('plugin://metadata.tvdb.com.python/','4','?action=getepisodedetails&url=8609547&pathSettings=%7b%22RatingS%22%3a0%2c%22absolutenumber%22%3afalse%2c%22dvdorder%22%3afalse%2c%22language%22%3a%22en%22%2c%22token%22%3a%22eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTYyODI3NTEsImlkIjoiS29kaSIsIm9yaWdfaWF0IjoxNjE1Njc3OTUxfQ.zqeQ2JpaillB_skXnYb0_wq-ANule3wzpXrJij56MTtuJQbDUQI2qf3EHP5lW3ChWduEdh2dDF_gm_ZD4v6AWPxT1IGnoFWTCyhECH6jOCOxKKfWKNllCO0cH38uHR22F-isBa44OmwPGIifqNh2CYVi6kwZIQbG6JNQSkc_Zyx0q5O7iCxjAwQMGtgBeJpffVWLpR1Z9qI-T6auMxorONCMu1FY16JySYxqiovxML1FBqw8HsQPjiCdALY486kMlXfay5F6Nzc9qLvlZQh2gATc4wqluTyZYwPAoeYYFiN0CyG60PJbNWXbL58WLRletfx5sHcQsSuLJQ5yCVHm0A%22%7d','resume:false')
2021-08-13 14:28:50.103 T:347     DEBUG <general>: GetLanguageInvoker - Reusing LanguageInvokerThread 4 for script /config/.kodi/addons/metadata.tvdb.com.python/scraper.py
2021-08-13 14:28:50.103 T:349      INFO <general>: initializing python engine.
2021-08-13 14:28:50.103 T:349     DEBUG <general>: CPythonInvoker(4, /config/.kodi/addons/metadata.tvdb.com.python/scraper.py): start processing
2021-08-13 14:28:50.103 T:349     DEBUG <general>: CPythonInvoker(4, /config/.kodi/addons/metadata.tvdb.com.python/scraper.py): entering source directory /config/.kodi/addons/metadata.tvdb.com.python
2021-08-13 14:28:50.103 T:349     DEBUG <general>: CPythonInvoker(4, /config/.kodi/addons/metadata.tvdb.com.python/scraper.py): instantiating addon using automatically obtained id of "metadata.tvdb.com.python" dependent on version 3.0.0 of the xbmc.python api
2021-08-13 14:28:50.104 T:349     DEBUG <general>: metadata.tvdb.com.python: Called addon with params: ['plugin://metadata.tvdb.com.python/', '4', '?action=getepisodedetails&url=8609547&pathSettings=%7b%22RatingS%22%3a0%2c%22absolutenumber%22%3afalse%2c%22dvdorder%22%3afalse%2c%22language%22%3a%22en%22%2c%22token%22%3a%22eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTYyODI3NTEsImlkIjoiS29kaSIsIm9yaWdfaWF0IjoxNjE1Njc3OTUxfQ.zqeQ2JpaillB_skXnYb0_wq-ANule3wzpXrJij56MTtuJQbDUQI2qf3EHP5lW3ChWduEdh2dDF_gm_ZD4v6AWPxT1IGnoFWTCyhECH6jOCOxKKfWKNllCO0cH38uHR22F-isBa44OmwPGIifqNh2CYVi6kwZIQbG6JNQSkc_Zyx0q5O7iCxjAwQMGtgBeJpffVWLpR1Z9qI-T6auMxorONCMu1FY16JySYxqiovxML1FBqw8HsQPjiCdALY486kMlXfay5F6Nzc9qLvlZQh2gATc4wqluTyZYwPAoeYYFiN0CyG60PJbNWXbL58WLRletfx5sHcQsSuLJQ5yCVHm0A%22%7d', 'resume:false']
2021-08-13 14:28:50.104 T:349     DEBUG <general>: metadata.tvdb.com.python: Find info of episode with id 8609547
2021-08-13 14:28:51.546 T:349     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'Exception'>
                                                   Error Contents: "arrow" module is not available
                                                   Traceback (most recent call last):
                                                     File "/config/.kodi/addons/metadata.tvdb.com.python/scraper.py", line 5, in <module>
                                                       actions.run()
                                                     File "/config/.kodi/addons/metadata.tvdb.com.python/resources/lib/actions.py", line 46, in run
                                                       urllib.parse.unquote_plus(params["url"]), images_url, settings)
                                                     File "/config/.kodi/addons/metadata.tvdb.com.python/resources/lib/episodes.py", line 99, in get_episode_details
                                                       ratings(liz, ep, True, settings)
                                                     File "/config/.kodi/addons/metadata.tvdb.com.python/resources/lib/ratings.py", line 16, in ratings
                                                       liz, item, is_episode, settings)
                                                     File "/config/.kodi/addons/metadata.tvdb.com.python/resources/lib/ratings.py", line 42, in _get_and_set_trakt_ratings
                                                       trakt_rating = get_trakt_rating_and_votes(item.id, is_episode)
                                                     File "/config/.kodi/addons/metadata.tvdb.com.python/resources/lib/trakt_rating.py", line 18, in get_trakt_rating_and_votes
                                                       result_list = Trakt['search'].lookup(tvdb_id, 'tvdb', extended='full')
                                                     File "/config/.kodi/addons/script.module.trakt/lib/trakt/interfaces/search.py", line 104, in lookup
                                                       return SearchMapper.process_many(self.client, items)
                                                     File "/config/.kodi/addons/script.module.trakt/lib/trakt/mapper/search.py", line 36, in process_many
                                                       return [item for item in [cls.process(client, item, **kwargs) for item in items] if item]
                                                     File "/config/.kodi/addons/script.module.trakt/lib/trakt/mapper/search.py", line 36, in <listcomp>
                                                       return [item for item in [cls.process(client, item, **kwargs) for item in items] if item]
                                                     File "/config/.kodi/addons/script.module.trakt/lib/trakt/mapper/search.py", line 29, in process
                                                       return func(client, item, **kwargs)
                                                     File "/config/.kodi/addons/script.module.trakt/lib/trakt/mapper/search.py", line 147, in episode
                                                       episode = cls.construct(client, 'episode', i_episode, keys, **kwargs)
                                                     File "/config/.kodi/addons/script.module.trakt/lib/trakt/mapper/core/base.py", line 115, in construct
                                                       return Episode._construct(client, keys, item, **kwargs)
                                                     File "/config/.kodi/addons/script.module.trakt/lib/trakt/objects/episode.py", line 170, in _construct
                                                       episode._update(info, **kwargs)
                                                     File "/config/.kodi/addons/script.module.trakt/lib/trakt/objects/episode.py", line 159, in _update
                                                       self.first_aired = from_iso8601_datetime(info.get('first_aired'))
                                                     File "/config/.kodi/addons/script.module.trakt/lib/trakt/core/helpers.py", line 132, in from_iso8601_datetime
                                                       raise Exception('"arrow" module is not available')
                                                   Exception: "arrow" module is not available
                                                   -->End of Python script error report<--
                                                   
2021-08-13 14:28:51.547 T:349     DEBUG <general>: onExecutionDone(4, /config/.kodi/addons/metadata.tvdb.com.python/scraper.py)
2021-08-13 14:28:51.621 T:349      INFO <general>: Python interpreter stopped
2021-08-13 14:28:51.6
```

**Comment by matthuisman** [comment]
No ideas sorry. Keep tryin

**Comment by bossanova808** [comment]
I haven't yet seen this again, all going ok now, with no exceptions in the log.  Perhaps the containers just needed an extra re-start..something to do with the install/auto-enable not quite taking on the same run??

Or maybe it's just some wierd python path through the scraper that only comes up now and again.  

Seems to be working ok, so will close this again.  Thanks again!
